- package.json
- src/Playroom/Playroom.js
- src/Playroom/Preview/Preview.js
This also ensures that we lint in CI as part of `npm test`.
> fix: Fix propTypes and lint warnings

- README.md
> docs: Add Fannypack to demos list

- src/Playroom/Frame.js
Either use uppercase when updating state (this PR) or lowercase when initializing state (and read).
> fix(FrameComponent): Map state correctly to support HMR

- cypress/integration/smokeTest.js
- cypress/support/commands.js
- cypress/support/index.js
- cypress/support/utils.js
- src/Playroom/Preview/Preview.less
- src/Playroom/Preview/Preview.tsx
- src/Playroom/Toolbar/Toolbar.tsx
- src/Playroom/ToolbarItem/ToolbarItem.tsx
- src/Playroom/ViewPreference/ViewPreference.tsx
Add more integration tests to cover url handling, visible widths toggling, copy to clipboard and assert frames are interactable.
> test: Add more integration tests

- src/Playroom/Playroom.tsx
- src/Playroom/variables.less
Fix viewport overflow on small screens and update the new max number of toolbar items.
> fix: Improve handling of editor size on small screens

- README.md
> docs: Added AutoGuru's Overdrive

- src/Playroom/Frames/frameSrc.d.ts
- src/Playroom/Frames/frameSrc.js
- src/Playroom/Frames/frameSrc.ts
> fix: Resolve frameSrc not found warning

- README.md
hey, how are ya? just a very important change here, i'd say almost urgent. anyway, just wanna rename fannypack to bumbag coz fannypack is a thing of the past now lmao. 
regards,
jake
> Rename Fannypack to Bumbag in Demos

- README.md
Add [Cubes](https://github.com/Trampoline-CX/cubes) in Readme.
Delightfully simple building blocks for quick prototyping 🚀
> docs: Add Cubes library in Readme

- src/Playroom/Preview.tsx
Addresses https://github.com/seek-oss/playroom/pull/187#issuecomment-700165520
> fix: Only nest user content inside FrameComponent in preview mode

- cypress/support/utils.js
- src/Playroom/CodeEditor/CodeEditor.less
- src/Playroom/CodeEditor/CodeEditor.tsx
- src/Playroom/SplashScreen/SplashScreen.less
- src/Playroom/variables.less
Adding line numbers into the editor. Also improving the syntax error marker and message to suit the new gutter size.
> feat(editor): Add line numbers

- src/Playroom/CodeEditor/CodeEditor.less
- src/Playroom/CodeEditor/CodeEditor.tsx
- src/Playroom/variables.less
Closes https://github.com/seek-oss/playroom/issues/206
> feat(editor): Add code folding and highlight the current line

- .github/workflows/preview-site.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/validate.yml
- package.json
Adding a snapshot workflow so I can test a branch on Braid's playroom.
> Add snapshot workflow

- README.md
As per https://github.com/badges/shields/issues/8671
> Use new badge routes

- src/Playroom/SettingsPanel/SettingsPanel.tsx
Sorting the keyboard shortcuts now that we have more of them (and will be adding more).
> Sort shortcuts alphabetically

- .changeset/plenty-poets-nail.md
- src/Playroom/FramesPanel/FramesPanel.css.ts
- src/Playroom/FramesPanel/FramesPanel.tsx
- src/Playroom/SettingsPanel/SettingsPanel.css.ts
- src/Playroom/SettingsPanel/SettingsPanel.tsx
> Move tab title field from settings panel to frames panel

- .changeset/four-peaches-attack.md
- src/Playroom/Snippets/Snippets.tsx
Couple follow up changes for https://github.com/seek-oss/playroom/pull/371
> re: Snippets bug - update changeset and minor refactor

- .changeset/major-turtles-fall.md
- .changeset/major-waves-say.md
- cypress/e2e/toolbar.cy.ts
- cypress/support/utils.ts
- src/Playroom/Frames/Frames.css.ts
- src/Playroom/Frames/Frames.tsx
- src/Playroom/FramesPanel/FramesPanel.tsx
- src/Playroom/Playroom.tsx
- src/StoreContext/StoreContext.tsx
- src/index.js
- utils/index.d.ts
> Add 'Fit to window' frame width option, fix frame name styling bug

- bin/cli.cjs
- eslint.config.mjs
- lib/build.js
- lib/getStaticTypes.js
- lib/makeWebpackConfig.js
- lib/provideDefaultConfig.js
- lib/start.js
Keen to add this early to make upcoming changes easy to manage
> Apply import order rules

- .changeset/beige-things-speak.md
- lib/makeWebpackConfig.js
- src/entries/frame.tsx
- src/entries/index.tsx
- src/entries/preview.tsx
In preparation for the UI uplift, we are structuring the repo and decoupling from “prop drilling” pattern that will hinder our speed of experimentation with UI reshuffles.
This is the first of a set of PRs to follow.
> refactor: Improve internal structure enable UI flexibility
