seek-oss/playroom

- lib/makeWebpackConfig.js
By setting the `publicPath` to a blank string, the generated files can be hosted within nested paths. Otherwise, right now, the generated HTML will attempt to resolve files relative to the root URL.
> fix: Allow hosting within nested paths

- lib/start.js
> fix: Open correct URL if custom port is supplied

- bin/cli.js
- lib/build.js
This fixes two issues with `playroom build`:
- In the case of an error, it wasn't being logged to the terminal.
- Only errors with webpack itself were being caught, not errors with the code being compiled. For example, a syntax error in your component library wouldn't fail the build.
> fix(build): Handle build errors

- examples/material-ui/playroom.config.js
- examples/reakit/playroom.config.js
- lib/makeDefaultWebpackConfig.js
- lib/makeWebpackConfig.js
As you can see in the updated examples, this fixes an issue where you need to provide custom webpack config just to use modules and JSX in your configuration code. This ensures that you get a sensible baseline level of compilation for your source code, but allows you to easily override it when needed.
I'm planning to expand this further in the future, but this is an obvious starting point.
> feat: Add default webpack config, compile with Babel and support JSX

- src/Playroom/Playroom.js
Since react-codemirror calls `require('codemirror')` internally, it's possible that it ends up referencing a different version of CodeMirror than we expect. This manifests itself in syntax highlighting and autocomplete failing to work.
The fix for this is to explicitly pass in our own reference to CodeMirror, via the `codeMirrorInstance` prop. This ensures that `require('codemirror')` is no longer called by react-codemirror, and we're in full control of the version being used.
I've also refactored the code to use regular imports rather than using `require` because we no longer need to guard against rendering in a Node context (this is a relic from when Playroom used to be part of our pre-rendered style guide site), and it would have been really awkward to solve this using the existing …
> fix: Fix syntax highlighting and autocomplete

- src/Playroom/Playroom.js
Since this fix would have required some duplication, I also refactored the code so that we only generate a single CodeMirror React element, which is shared between docked and undocked layouts.
The actual fix was quite small—adding the following check to the Tab key handler:
```js
if (cm.somethingSelected()) {
cm.indentSelection('add');
} else {
...
}
```
> fix: Fix multi-line indentation

- README.md
Update README documentation to include extra config options that can be overwritten (`port` and `openBrowser`).
> docs(readme): Update docs to include extra config options

- lib/makeWebpackConfig.js
Webpack >= 4 doesn't need chunks to be sorted, and this option can cause builds to fail with errors that are difficult to debug.
In my case Webpack created circularly dependent chunks even after removing any circular imports in the module graph. As I mentioned above, the error that gets thrown is especially unhelpful:
```
$project/node_modules/toposort/index.j
s:35
throw new Error('Cyclic dependency' + nodeRep)
^
Error: Cyclic dependency
at visit ($project/node_modules/toposort/index.js:35:13)
<-- snipped about 30 more stack frames -->
```
With a bit of research I found https://github.com/jantimon/html-webpack-plugin/issues/870#issuecomment-370004105 which suggests `chunksSortMode: 'none'` as a workaround, and I've verified this prevents the error for my project. It also seems that this …
> fix: Disable chunk sorting in HtmlWebpackPlugin

- lib/index.js
- lib/makeWebpackConfig.js
- lib/start.js
- src/Playroom/Playroom.js
- src/Playroom/components.js
- src/Playroom/frameComponent.js
- src/Playroom/themes.js
- src/index.js
During local development, this adds hot module reloading to the three user-provided modules: `components`, `themes` and `frameComponent`. If any of these modules change, we update Playroom's local state which triggers a re-render with the updated code.
Since I needed access to the server port, I refactored the code to centralise config defaults. Previously, the port was only being defaulted in the one place it was used.
> feat: Add hot module reloading for components and themes

- src/Playroom/Playroom.js
- src/Playroom/WindowPortal/index.js
This PR applies the following fixes:
- Maintain undo history after formatting.
- Support formatting within undocked editor.
- Format current editor value, not last rendered code.
Why were these issues happening?
- We update the `key` for the editor when formatting, which causes a remount. This means we're actually rendering an entirely new editor without any undo history.
- We attach the keyboard shortcut to the window, but not to the new window that gets opened when undocking the editor.
- We were debouncing the `code` state update, which means that any attempt to read the current editor value was actually reading a snapshot of the last committed code, not necessarily what the user had most recently typed.
> fix: Fix Prettier formatting issues

- README.md
- examples/material-ui/package.json
- examples/material-ui/playroom/FrameComponent.js
- examples/material-ui/yarn.lock
- examples/reakit/playroom/FrameComponent.js
As reported [here](https://github.com/seek-oss/playroom/issues/62) the material-ui and (also the reakit example) are not working since moving away from `react-frame-component` as there is no `frameWindow` provided.
Given updated iframe solution switching to `window` directly should be fine now.
Fixes https://github.com/seek-oss/playroom/issues/62
> fix(examples): Use window in favour of deprecated frameWindow prop

- .travis.yml
- cypress.json
- cypress/integration/smokeTest.spec.js
- cypress/support/utils.js
- package.json
- src/Playroom/Playroom.js
- src/Playroom/Playroom.less
- yarn.lock
Migrates from `react-codemirror` to `react-codemirror2`.
Also upgrading cypress and switching CI over to `yarn` so it honours the lock file.
Closes https://github.com/seek-oss/playroom/issues/32.
> fix(deps): Migrate to react-codemirror2

- package.json
- yarn.lock
Provide mechanism for running cypress against the built playroom (`yarn cypress`) or against the running webpack-dev-server (`yarn cypress:dev`)
> ci(cypress): Build playroom for smoke test

- cypress/integration/smokeTest.spec.js
- cypress/support/index.js
- cypress/support/utils.js
- package.json
- src/Playroom/Playroom.js
- yarn.lock
Fixes the prettier formatting bug introduced in the CodeMirror upgrade, plus adding a cypress test to cover the formatting scenario.
(Also upgrading lodash to get rid of the vulnerability warning)
Closes https://github.com/seek-oss/playroom/issues/76
> fix: Resolve prettier formatting error

- package.json
- src/index.js
- utils/index.js
- yarn.lock
Compressing the code encoded in the URL should reduce the URL length by over 50% in most cases. To allow for backwards compatibility with old URLs, the new query param is encoded as JSON. Playroom will fall back to the old format if `JSON.parse` fails.
> feat: Compress code in URL

- lib/getStaticTypes.js
Currently, types aren't captured for this config:
```
const playroomConfig = {
cwd: path.resolve('../my-design-system'),
};
```
This architecture being common in a monorepo, this little change does the trick.
> fix: Support types from files outside of cwd

- src/Playroom/Preview/Preview.less
The `:before` pseudo element that provides an animated box shadow around each frame is currently swallowing clicks on the frame content, so this PR adds `pointer-events: none` to ensure that clicks go through correctly.
> fix: Ensure frames are interactive

- src/Playroom/ToolbarItem/ToolbarItem.less
The ToolbarItem content is broken on Firefox.
**Before:**
**After:**
> fix: Align ToolbarItem content to center

- src/Playroom/Preview/Preview.less
This ensures that frames are horizontally centred when the total width of all frames is lower than the outer viewport width. When the frames can no longer fit on the screen, the layout is exactly the same as today, seemingly left-aligned with a horizontal scrollbar.
Before:
After:
This improvement is especially noticeable when the code pane is docked to the right:
> fix: Align frames to centre

- @types/babel__standalone.d.ts
- package.json
- src/utils/compileJsx.ts
- tsconfig.json
- yarn.lock
- Allow props spreading alongside inline props
Fixes https://github.com/seek-oss/playroom/issues/118
> fix: Compile with babel/standalone instead of buble

- src/Playroom/Playroom.less
- src/Playroom/Playroom.tsx
- src/Playroom/Preview/Preview.less
- src/Playroom/Toolbar/Toolbar.less
- src/Playroom/Toolbar/Toolbar.tsx
- src/Playroom/Toolbar/icons/ChevronSvg.less
- src/Playroom/Toolbar/icons/ChevronSvg.tsx
- src/Playroom/variables.less
- src/StoreContext/StoreContext.tsx
- Toolbar status messages no longer obscured by code editor, eg. copy to clipboard success message and invalid cursor position for snippets.
- Remove currently broken undock editor feature
- Improved UX switching between toolbar panels
- Hide/minimise the editor to focus on preview frames.
> fix: Toolbar status messages fixes & support hiding editor

- .github/workflows/release.yml
- .github/workflows/validate.yml
A couple of tweaks to the actions setup:
- Tweak Release step name, as it's not deploying a site, only publishing to npm
- Run Validate on pull_request event to run in this repo context for forks/PRs
- Make PreviewSite not a required action.
> ci: Run validate action on forks

- src/Playroom/CodeEditor/CodeEditor.tsx
- src/StoreContext/StoreContext.tsx
With the editor now checking the validity of the cursor position on every cursor activity, there is a race condition where the store has a mismatched combination of code and cursor.
Now when the editor notifies of a cursor change, it sends the current code with the payload to ensure the validity check always has all the information required.
Fixes https://github.com/seek-oss/playroom/issues/151
> fix: Cannot read property ‘slice’ of undefined error

- src/Playroom/CodeEditor/CodeEditor.tsx
Been using Playroom for a few weeks now and from what I can tell there is no way to get hints, other than pressing space, when you split the props by line.
```jsx
<Button
type="button"
// Right here I have to insert a space to get hints which I then have to remove
/>
```
With this very little change you can simply press `Ctrl+Space` which is what you're probably used to if you use any IDE.
The hints addon is quite good and does what you expect when you trigger the hints on "unsuspected" places. In other words, this does not seem to break anything or add unwanted behaviour.
Also want to thank you guys for this piece of software, great work you're doing. Hope I can contribute more than this in the future 🙏
> feat: Show hints on Ctrl+Space

- README.md
- cypress/projects/basic/playroom.config.js
- examples/seek-style-guide/playroom.config.js
- lib/start.js
- src/Playroom/Frames/Iframe.tsx
- src/index.d.ts
Hi! We’re looking at integrating Playroom on our design system style guide at [NerdWallet](https://www.nerdwallet.com/). Given Playroom’s inherent ability to execute arbitrary code, one of our security engineers had some recommendations:
1. Move the site to its own domain where cookies for other NerdWallet applications will not be available
1. Use the `sandbox` attribute in Playroom’s iframe to sandbox arbitrary code execution
This PR is about the second item and implements the `sandbox` attribute in the `<Iframe>` component driven by `playroom.config.js` config. Credit for the implementation also goes to @mhensley-nw.
This security concern was also raised in #125.
Like #125 mentions, using `sandbox=”allow-scripts”` breaks Webpack hot module replacement in development. This is because …
> feat: Add iframeSandbox config

- cypress/support/utils.js
- src/Playroom/CodeEditor/CodeEditor.tsx
- src/Playroom/Preview.tsx
- src/Playroom/PreviewPanel/PreviewPanel.tsx
- src/StoreContext/StoreContext.tsx
- src/utils/params.ts
- utils/index.d.ts
- utils/index.js
- yarn.lock
This change ensures only the `code` param in the URL is modified. This allows custom params to be retained. 
Note: A lockfile refresh needed to be done for a babel issue unrelated to this change.
> fix: Preserve extra params in URL

- utils/index.d.ts
- utils/index.js
Add theme to compressParams so PreviewUrl works with multibranding.
> fix: Add theme to compressParams

- README.md
Remove Header & Footer in SEEK Style Guide example: components don't exist anymore.
> docs: Remove broken seek-style-guide link

- src/Playroom/Preview.less
- src/Playroom/Preview.tsx
Isolates the rendered content in Preview mode to its own stacking context to ensure it's below the `SplashScreen`.
> fix(Preview): Resolve SplashScreen rendering behind content

- src/Playroom/Frames/Frames.less
- src/Playroom/Frames/Frames.tsx
Fix bug on small windows/preview areas where the preview frame would be pushed outside of it's container.
> fix: Frame overflow bug at super small resolutions

- src/Playroom/Frames/Frames.tsx
Specifying a width with any unit other than `px` results in the following:
ie; it always appends `px`.
This change uses the assumption that when the width value ends in a number, it is an implicit `px` value, otherwise, it leaves it alone and uses the exact value supplied for display.
> Correctly display widths specified in non-px units

- src/Playroom/Frames/Frames.less
When there are fewer frames than the viewport width the frames should be centered in the preview area. I broke that with the last PR.
> fix: Center preview frames when fewer than viewport

- README.md
We've got a themed example of playroom running on our design system, Mesh, that we'd like to add. 🙂
> docs: Add Mesh example to README

- src/Playroom/Preview.less
- src/Playroom/Preview.tsx
This PR creates two separate stacking contexts for the rendered content and the splash screen, ensuring that the splash screen is always above the rendered content (even if it contains elements with very high z-indexes), but also ensuring that the rendered content is still interactive.
Closes #198 
Fixes #197
> fix: Ensure rendered content is interactive in preview mode

- src/Playroom/Frames/Frames.tsx
Fixes the flashing of render errors while typing in the editor.
Closes #210
> fix: Render last valid code when current code is invalid

- cypress/integration/smoke.js
- lib/makeWebpackConfig.js
- utils/index.js
Also appending a trailing slash to the preview path for consistency of url handling across different servers.
> fix: Ensure preview mode loads static assets correctly

- lib/makeWebpackConfig.js
Mistakenly set the base path for the preview route rather than relatively referencing the parent folder of the preview document.
> fix: Set preview mode public path correctly

- lib/makeDefaultWebpackConfig.js
- lib/makeWebpackConfig.js
According to [webpack documentation](https://webpack.js.org/configuration/module/#ruleuse), `rule.use` should be an array. I believe it was once allowed to be an object and is still backwards compatible.
For more background, I use [external-svg-sprite-loader](https://github.com/bensampaio/external-svg-sprite-loader) which iterates over the rules/loaders and expects `rule.use` to be an array per the webpack docs. Trying to use playroom but running into bensampaio/external-svg-sprite-loader#58 at the moment, this change should fix the issue.
> fix: Correct rule.use to an array

- lib/getStaticTypes.js
This PR should fix #247 
`undefined` is passed to `path.dirname`, on projects with no TS config file.
> fix: prevent exception on start when no TS config is found

- lib/start.js
When attempting to import external fonts into playroom, I've been getting the following error:
Not sure why my origin would be `null`, but it seems that adding `Access-Control-Allow-Origin` to the dev server config fixes the issue.
> Add `Access-Control-Allow-Origin` to playroom dev server

- .github/workflows/release.yml
Trying to get Version Packages PR to run workflow actions. Removing the token from the checkout step to align with the working implementation we have in [Vocab](https://github.com/seek-oss/vocab/blob/master/.github/workflows/release.yml).
🎲
> ci: Remove token from release checkout step

- .github/workflows/release.yml
Run the changesets release step as the `seek-oss-ci` user.
> ci: Run changesets release as seek-oss-ci user

- .changeset/wicked-emus-jog.md
- src/Playroom/CodeEditor/CodeEditor.tsx
The number of times I've tried to move a block of code up or down using Alt-Up in Playroom must be almost equal to the numbers of lines I've written in Playroom. It feels like checking my empty wrist when I've forgotten my watch.
These oversights have been corrected, and I have ascended to heights of programming efficiency hitherto undreamt of. And now you can too.
They work just like VSCode's versions.
These implementations were mostly lifted from the codemirror5 [sublime text keymap], with a bit of editing to make them work how I think they should work.
[Preview site] for testing it out, or I've [snapshotted it into Braid][snap] if that's your preference.
[sublime text keymap]: https://codemirror.net/5/keymap/sublime.js
[preview site]: …
> Add line editing keyboard shortcuts

- .github/workflows/preview-site.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/validate.yml
- package.json
- pnpm-lock.yaml
- scripts/postCommitStatus.js
Currently, when a preview deploy gets published, the link is added as a PR status to be a little easier to find. This isn't all that helpful if you don't have a PR yet, and digging around in the action logs isn't ideal either.
Have added the link to an action summary, similar to changesets-snapshot.
I've also upgraded the pnpm action in this PR, as the existing version used deprecated actions API, so the [warning annotations] that used to come up [don't anymore].
[warning annotations]: https://github.com/seek-oss/playroom/actions/runs/4333280893
[don't anymore]: https://github.com/seek-oss/playroom/actions/runs/4333287804
> Add a preview link to the GitHub action summary

- .github/workflows/release.yml
...so the commit triggers GitHub actions.
This happened before https://github.com/seek-oss/vocab/pull/111
> Use GitHub token when checking out

- .changeset/tidy-cows-complain.md
- lib/makeWebpackConfig.js
> Allow overriding Webpack module rules

- .changeset/lazy-boxes-speak.md
- .eslintrc
- README.md
- bin/cli.cjs
- package.json
As a consumer, I want to be able to define my playroom config using ESM compatible JS code. I noticed today when trying this behaviour out that sadly playroom does not currently support this, so I've prepared this PR to add support for this behaviour.
As this PR replaces `require` with `import` for loading config files, it is important that the `bin/cli.js` file is still loaded as CommonJS code. To force this behaviour (when users might specify `"type":"module"` in their `package.json`s) I have renamed it `bin/cli.cjs`.
Unsure if this is best released as a minor or major change. I can modify the changeset command as needed.
> Feat: add support for loading mjs config files

- .changeset/thick-mails-poke.md
- src/Playroom/CodeEditor/CodeEditor.css.ts
Currently there's no way to tell that there's a tooltip on the error marker, other than waiting
> Make the error marker hoverable

- .changeset/six-spoons-change.md
- lib/makeWebpackConfig.js
https://github.com/seek-oss/playroom/pull/309 seems to have broken `playroom build`. This wasn't caught during CI as the preview build runs a script from the repo root, so the path resolves correctly. However it's incorrect in any other case, e.g. using `playroom` as a dependency.
Have confirmed that this fix works by testing [Braid](https://github.com/seek-oss/braid-design-system)'s playroom build.
Ideally we'd have proper fixtures (i.e. make the repo into a monorepo) that we could test in isolation, but we're not there yet.
Fixes #311.
> Fix `playroom build` by making favicon path relative to webpack config

- .changeset/young-turkeys-turn.md
- cypress/e2e/keymaps.cy.js
- src/Playroom/CodeEditor/keymaps/wrap.ts
When using the "Wrap selection in tag" command (`⌘` + `⇧` + `,`) on a single line of text that includes leading whitespace, the start cursor ends up in the wrong position:
https://github.com/seek-oss/playroom/assets/33821218/34c25a8d-dd82-46f3-9e51-893c496a32e3
This change subtracts the leading whitespace when calculating the position of the start cursor.
> Fix bug in "Wrap selection in tag" command

- .changeset/popular-dingos-walk.md
- src/StoreContext/StoreContext.tsx
Prevent new Playroom tabs with no set title from loading a recently used title.
New Playroom tabs should now have no set title by default.
> Prevent new Playroom tabs from loading previously used titles

- cypress/e2e/editor.cy.js
- cypress/e2e/scope.cy.js
- cypress/e2e/smoke.cy.js
- cypress/e2e/toolbar.cy.js
- cypress/e2e/urlHandling.cy.js
- cypress/support/utils.js
- package.json
- pnpm-lock.yaml
Converting some of `then`s into [`should`](https://docs.cypress.io/api/commands/should)s and utilizing [`its`](https://docs.cypress.io/api/commands/its#Assertions) lets us lean into cypress' retry mechanisms, so we don't need to wait for iframe loads or add tons of delays during interactions anymore.
This blog post came in handy for the iframe stuff: https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress
The only exception is the `autocompletes` test as that relies on the autocomplete options to have rendered before the `enter` key is pressed.
Also bumped cypress to v13. Would be good to run CI a few times to confirm that it's stable enough for our liking.
> Remove cypress delays, modify assertions to leverage cypress' retryability

- .changeset/eighty-pears-deny.md
- src/Playroom/SettingsPanel/SettingsPanel.tsx
This change sorts shortcuts by most frequently and most widely used, instead of alphabetical order.
More advanced shortcuts (mainly for developers) are moved to the bottom of the list.
Related shortcuts (e.g. "Add cursor to next line" and "Add cursor to prev line") are kept together.
> Improve keyboard shortcuts order

- .changeset/six-fans-appear.md
- package.json
- pnpm-lock.yaml
None of the breaking changes in v5 affected our usage. See [migration guide](https://github.com/webpack/webpack-dev-server/blob/master/migration-v5.md).
> Upgrade `webpack-dev-server` to v5

- .changeset/breezy-monkeys-cough.md
- lib/provideDefaultConfig.js
- package.json
- pnpm-lock.yaml
Replaces [`current-git-branch`](https://www.npmjs.com/package/current-git-branch), a relatively simple, yet likely unmaintained package, with a call to `git branch --show-current`.
> Remove dependency on `current-git-branch`

- .changeset/early-dogs-peel.md
- package.json
- pnpm-lock.yaml
- src/Playroom/Frame.tsx
- src/Playroom/Preview.tsx
- src/StoreContext/StoreContext.tsx
- src/utils/params.ts
The platform-native `URLSearchParams` has broad browser support, so we don't really have a need for `query-string` anymore.
> Replace `query-string` dependency with `URLSearchParams`

- .changeset/many-trains-cheat.md
- cypress/e2e/keymaps.cy.js
- src/Playroom/CodeEditor/keymaps/comment.ts
Fixes an issue where full line expression slots outside any JSX tags would be line commented rather than block commented.
https://github.com/seek-oss/playroom/assets/33821218/211da86d-31cc-438e-a823-645295b18daa
> Refactor logic to determine comment type for "Toggle comment" command

- cypress/support/utils.js
Currently, Cypress tests in CI are unreliable and will only pass a slim majority of the time. This change adds some more time for new search-related shortcut tests to ensure Playroom has settled after shortcuts are triggered. This branch has passed Cypress in CI over 10 times and is proving more reliable.
* Increase wait times for "Find", "Find and replace" and "Jump to line" functions in Cypress tests
* Remove `force` from `typeInSearchField` function
> Fix reliability issues in Cypress tests for search related keyboard shortcuts

- .changeset/sweet-buses-taste.md
- package.json
- pnpm-lock.yaml
Upgraded `lz`string` to 1.5.0, which also removes the need for `@types/lz-string`
> Upgrade `lz-string` to version 1.5.0

- .changeset/strange-zoos-compare.md
- src/Playroom/SettingsPanel/SettingsPanel.css.ts
- src/Playroom/SettingsPanel/SettingsPanel.tsx
- src/Playroom/ToolbarItem/ToolbarItem.tsx
The element wrapping these icons wasn't really doing anything, other than causing the icons to be laid out in flow layout, resulting in extra bottom padding because of line height. Rather than setting `line-height: 0` on the wrapping elements, I just removed them so the icons are now using flex, so they don't end up with the line height padding.
Before:
After:
> Fix centering of settings panel and toolbar icons

- .changeset/rich-geese-confess.md
- lib/start.js
Prevent the default webpack dev server error overlay from blocking the preview frames in `start` mode.
Playroom handles it's own errors, and this would block the preview frames and need to be dismissed manually.
> start: Disable webpack error overlay

- .changeset/green-plants-cheer.md
- cypress/e2e/urlHandling.cy.ts
- src/Playroom/FramesPanel/FramesPanel.tsx
- src/Playroom/Playroom.tsx
Previously the document `title` would only update when the frames panel is open.
The title is now correctly reflected from the url on page load.
> Apply `title` from url on page load

- .changeset/clever-keys-act.md
- package.json
- pnpm-lock.yaml
- src/Playroom/Playroom.css.ts
- src/Playroom/Playroom.tsx
- src/Playroom/Toolbar/Toolbar.css.ts
- src/Playroom/Toolbar/Toolbar.tsx
- src/Playroom/toolbarConstants.ts
- src/StoreContext/StoreContext.tsx
See changeset.
Setting the defaults to 40% as these look pretty good even at smaller screen sizes, but open to suggestions if this should be different.
> Save code editor size preference as percentage

- cypress/projects/basic/playroom.config.js
- cypress/projects/typescript/playroom.config.js
Ensure both `basic` and `typescript` projects have an explicit port, similar to `themed`.
This change prevents some issues running the `typescript` project locally, with the port not falling back to the expected value.
Adding the expected port to the `basic` project as well for explicitness and consistency.
> Provide explicit port for all projects

- .changeset/four-peaches-attack.md
- cypress/e2e/snippets.cy.ts
- src/Playroom/Snippets/Snippets.tsx
- src/Playroom/Toolbar/Toolbar.tsx
Resolves https://github.com/seek-oss/playroom/issues/368
This issue occurs when the user moves their cursor over a snippet in the snippet panel, while the panel is closing.
This triggers the frames to enter a mode for previewing snippets, which is only ended when the snippets panel is initially closed.
This change prevents snippets from being previewed after the panel begins to close.
> fix: Disable snippet previews while snippet panel is closing

- .changeset/ninety-pugs-swim.md
- cypress/e2e/urlHandling.cy.ts
- src/Playroom/CodeEditor/CodeEditor.tsx
- src/Playroom/Playroom.tsx
- src/StoreContext/StoreContext.tsx
- src/index.d.ts
- src/utils/usePreviewUrl.ts
- utils/index.d.ts
- utils/index.js
See changeset
Last feature I want to get in before cutting a release
> Save editor hidden status to Playroom url

- .changeset/green-bikes-doubt.md
- package.json
- pnpm-lock.yaml
- src/Playroom/Playroom.tsx
Resolves https://github.com/seek-oss/playroom/issues/373
Providing explicit `zIndex` to resizable handles to ensure they are stacked above the code editor component. Fixes issue introduced with `re-resizable` patch release [here](https://github.com/bokuweb/re-resizable/pull/827/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R982)
> fix: Update `re-resizable` dependency and fix stacking order issue

- .changeset/nasty-brooms-brush.md
- lib/makeWebpackConfig.js
Playroom has its own webpack config, and has the ability for consumers to provide their own, which are both merged to create a single webpack config.
The merge matches rules, i.e. determines their uniqueness only by comparing the `test` property of a rule. So if a consumer tries to add a module rule with the same test as one of playroom's own configs, they will be treated as equal and thus one will override the other.
e.g.
```ts
const playroomConfig = {
{
test: /\.css$/,
include: path.dirname(require.resolve('codemirror/package.json')),
use: [MiniCssExtractPlugin.loader, require.resolve('css-loader')],
},
}
const consumerConfig = {
{
test: /\.css$/,
include: /my_files/,
use: "style-loader",
},
}
``` 
In the above example, both rules are considered equal, so one will take precedence, …
> Tighten webpack rule merge rules to prevent clashes

- .changeset/nasty-brooms-brush.md
- lib/makeWebpackConfig.js
Revert #376. This was causing issues with our internal usage of playroom. We rely on overriding playroom's `.css` file loading, but making the webpack merge rules stricter has made it impractical to override this rule (it required explicitly targeting codemirror within playroom's node modules). See https://github.com/seek-oss/playroom/pull/376#issuecomment-2481898315 for further discussion.
> Revert "Tighten webpack rule merge rules to prevent clashes (#376)"

- .changeset/slow-plums-bake.md
- lib/makeWebpackConfig.js
Playroom uses `VanillaExtract` to extract and process CSS files, specifically `.css.ts` files. While the webpack loader rule correctly limits the scope of this loader on playroom's own source code, the plugin itself isn't scoped, and as such, it sends up processing every single `.css.[t|j]s` file it can find, including those from the consumer's codebase, `node_modules`, etc..
This problematic, and leads to a whole range of issues, making Playroom unusable if your UI Library has `.css.[j|t]s` files, or even if one of your dependencies has it.
> I haven't found any mention of the plugin being scoped to the entire project by default, as their [documentation](https://vanilla-extract.style/documentation/integrations/webpack/#configuration) page is non-exhaustive, however I can confirm this to …
> Restrict VanillaExtract plugin to playroom's source `.css.ts` files only

- .changeset/few-coats-smash.md
- package.json
- pnpm-lock.yaml
- src/Playroom/palettes.ts
Since the release of Safari 18, [relative color syntax](https://caniuse.com/?search=relative%20color) and [`color-mix`](https://caniuse.com/?search=color-mix) have adequate browser support and should be bug-free. This means we can safely replace `polished` with native CSS.
`polished` was only used at build-time, so this doesn't affect bundle size at all.
I checked all the colors affected by these changes. In most cases, the colors are identical (when converted to `rgb`), with a few having slightly different values, e.g. the blue channel increases by 1. I think this is acceptable.
Additionally, usage of `rgba` was replaced with `rgb` as `rgba` is considered legacy and `rgb` is [recommended](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#:~:text=it%20is%20recommended%20to%2 …
> Replace `polished` dependency with CSS relative color syntax and `color-mix`

- .changeset/small-rules-bake.md
- src/Playroom/CodeEditor/CodeEditor.tsx
- src/Playroom/SettingsPanel/SettingsPanel.tsx
- src/Playroom/Toolbar/Toolbar.tsx
The current shortcut (⌘⇧C on Mac) conflicts with the dev tools inspector mode shortcut in Chrome (and other browsers) which is very useful in Playroom.
Removing this shortcut to prevent the conflict, as I suspect it does not have much use.
> Remove keybinding for copying Playroom link to clipboard

- .changeset/clean-pets-push.md
- lib/makeWebpackConfig.js
- src/preview.js
Making this change to improve tab management with preview links, and as an additional security measure to differentiate Playroom Previews/prototypes from genuine sites.
> Ensure favicon is displayed on Preview links

- .changeset/moody-poets-cross.md
- src/Playroom/Frames/frameSrc.js
- src/utils/params.ts
Changes to search params trigger browser navigation. Practically this means that every time your playroom code changes, every iframe's query params are updated, which results in the browser reloading the iframe document (multiplied by the number of frames being shown), and doing a full React render, which is quite slow.
On the other hand, URL hash updates do not cause navigations, which is why `paramType` defaults to `hash`, as it is simply the better option. When the hash updates, the entire iframe doesn't reload. Instead, the new JSX is rendered by the existing React root, but obviously only a tiny part of the DOM has changed, so React update's the fraction of the DOM that has changed nearly instantly.
However, some users host their playroom behind some kind of internal auth. Redirects …
> Use URL hash for iframe params regardless of configured `paramType`

- .changeset/fluffy-shrimps-switch.md
- lib/index.js
Fixes #407.
Currently, all modules that handle CLI commands (`start` and `build`) are required during CLI execution, regardless of which command is being executed. This causes pollution of the `build` environment, as described in #407.
This PR fixes the issue by `require`ing the relevant command's module within that command's function.
> CLI: Only require modules that are relevant to the CLI command being executed

- .changeset/spicy-ants-push.md
- cypress/e2e/urlHandling.cy.ts
- src/Playroom/Playroom.css.ts
- src/Playroom/Playroom.tsx
- src/Playroom/Toolbar/Toolbar.css.ts
- src/Playroom/Toolbar/Toolbar.tsx
- src/Playroom/constants.ts
Breaking off this change before other layout changes, mainly bringing the toolbar out of the editor
> Improve editor animation, prevent searching editor when hidden

- .changeset/loose-states-rescue.md
- package.json
- pnpm-lock.yaml
- src/Playroom/Snippets/Snippets.tsx
This change makes it easy to add more snippets without making it harder to search through them to find the correct result
I have put a snapshot release to test in the Braid Design System Playroom.
> Try searching 'badge' in each of the following to compare
- [Current search](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4IgLgFgpgtlDOIBcBtE8pQNYCkD2ARogLoA0IA7gJYAmkiqIAYlWAARh5vUB2NeFEMQC%2BQA)
- [Improved search](https://seek-oss.github.io/braid-design-system/preview/fc5c12b473dd7e523a4a3b2f3703cbf9a7cf4aff/playroom/#?code=N4IgLgFgpgtlDOIBcBtE8pQNYCkD2ARogLoA0IA7gJYAmkiqIAYlWAARh5vUB2NeFEMQC%2BQA)
> Improve snippet search result sorting

- CHANGELOG.md
With the last release including migrating the `utils` entries to TypeScript which necessitated an internal build step, we overlooked adding the migration guide for the updated import paths.
The code and published package does not require changing (given we are still pre v1), but adding the migration guide to support the change.
> utils: Add migration guide

- cypress/e2e/toolbar.cy.ts
- cypress/support/utils.ts
- src/components/Frames/Frames.tsx
- src/components/FramesPanel/FramesPanel.tsx
- src/components/Playroom/Playroom.tsx
- src/components/Toolbar/Toolbar.tsx
- src/configModules/widths.ts
- src/contexts/StoreContext.tsx
- src/entries/index.tsx
- utils/index.ts
Refactor `widths` to be accessible via config module pattern rather than prop-drilling.
> refactor: Create and adopt `widths` config module

- src/components/Frames/Frames.tsx
- src/components/FramesPanel/FramesPanel.tsx
- src/components/Playroom/Playroom.tsx
- src/components/PreviewPanel/PreviewPanel.tsx
- src/components/PreviewPanel/ThemeSelector.tsx
- src/components/Toolbar/Toolbar.tsx
- src/configModules/themes.ts
- src/contexts/StoreContext.tsx
- src/entries/index.tsx
Expose `themeNames` via the `themes` config module, rather than prop-drilling.
> refactor: Expose `themeNames` via `themes` config module

- jest.config.mjs
- src/components/CodeEditor/CodeEditor.tsx
- src/components/Playroom/Playroom.tsx
- src/entries/index.tsx
- src/utils/componentsToHints.test.ts
- src/utils/componentsToHints.ts
Consume `components` via the config module, rather than prop-drilling.
> refactor: Consume `components` via config module

- .changeset/dull-kiwis-bake.md
- package.json
- pnpm-lock.yaml
- src/components/CodeEditor/CodeEditor.tsx
- src/components/Playroom/Playroom.css.ts
- src/components/Playroom/Playroom.tsx
- src/components/Playroom/ResizeHandle.css.ts
- src/components/Playroom/ResizeHandle.tsx
- src/components/Toolbar/Toolbar.tsx
- src/components/constants.ts
- src/css/delimiters.ts
- src/entries/frame.tsx
- src/entries/index.tsx
- src/entries/preview.tsx
Refactor the top-level layout of Playroom to use CSS Grid in preparation for upcoming UI features.
Additionally, migrate away from `re-resizable` package for panel resizing in favour of a custom implementation to improve UI performance.
> Migrate top-level layout to CSS Grid
